### ISSUE TITLE
File transfers get stuck at 100%

### ISSUE THREAD

**Issue by contrapunctus-1** [blurpy/kouchat-android#21] opened 2017-03-08 04:00 UTC
File transfers get stuck at 100% and stay there for long periods, and there seems to be no way to cancel them.

Sender -
Android v7.0, kernel 3.10.84-g478d03a
KouChat v.1.1.0, installed from F-Droid.

Receiver -
Android v6.0.1, kernel 3.18.20-perf+
KouChat v1.1.0, installed from F-Droid.

**Comment by blurpy** [comment] 2017-03-09 10:18
Every time, or just sometimes? Which devices are you using?

**Comment by contrapunctus-1** [comment] 2017-03-11 17:57
Just sometimes. Sender is a Moto G4 Plus, receiver is a OnePlus 3T.

**Comment by blurpy** [comment] 2018-07-08 09:03
The issue is because of the introduction of rate limiting of notification updates.

http://saket.me/android-7-nougat-rate-limiting-notifications/

> Turns out, Android has a rate-limiting system in place for notification updates to prevent apps from DDOS-ing the notification shade. Although it has existed since long, the limit was significantly reduced in Nougat from 50 updates to 10 updates every second to improve performance.

https://developer.android.com/guide/topics/ui/notifiers/notifications

> However, Android also applies a rate limit when updating a notification. If you post updates to a single notification too frequently (many in less than one second), the system might drop some updates.

I'm looking into a fix for this now.

**Comment by blurpy** [comment] 2018-07-08 16:56
It's fixed in version 1.1.1. To be released when I'm done testing and tweaking Android 8 support.

**Closed by blurpy** 2018-07-08 16:56 UTC
